### PR TITLE
Update dependencies to match v0.13.post1 Python package

### PR DESCRIPTION
**Pull request by jamesmyatt**
See:

- https://github.com/DistrictDataLabs/yellowbrick/blob/v1.3.post1/setup.py
- https://github.com/DistrictDataLabs/yellowbrick/blob/v1.3.post1/requirements.txt

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@conda-forge-admin, please rerender

**Comment by jamesmyatt** [comment]
@melonhead901 , I'm tempted to put Python >= 3.6 given that the rest are all EOL. What do you think?

**Comment by kellend-git** [comment]
Hi @jamesmyatt, thanks for the cleanup. I think either >= 3.4 or 3.6 is fine given the EOL as you say. I don't really have a preference I'll approve the PR and you can choose either one.

**Review by kellend-git — APPROVED** [review]

**Comment by jamesmyatt** [comment]
@melonhead901, let's just merge it as it is. Thanks.

**Comment by jamesmyatt** [comment]
@melonhead901 , I think you're the only one that can merge this

**Comment by kellend-git** [comment]
Sorry for the delay - merged

**Pull request merged**
